server:
  port: 8081
translate-api:
  url: http://localhost:5000/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/words_new
    username: postgres
    password: 3817!
  jpa:
    generate-ddl: false
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
